//////////////////////////////// Filter-product
export const allProducts = {
  clothing: [
    {
      id: 1,
      title: "Heritage Crew",
      price: 25,
      colors: ["white", "blue"],
      sizes: ["S", "M"],
      images: {
        front: "./src/image/clothing/heritage-crew-tshirt-1.jpg",
        back: "./src/image/clothing/heritage-crew-tshirt-2.jpg",
      },
      stock: 15,
    },
    {
      id: 2,
      title: "Nike Essential",
      price: 85,
      colors: ["black", "red"],
      sizes: ["L", "XL"],
      images: {
        front: "./src/image/clothing/insert-nike-1.jpg",
        back: "./src/image/clothing/insert-nike-2.jpg",
      },
      stock: 10,
    },
    {
      id: 3,
      title: "Oversized Sweat",
      price: 45,
      colors: ["gray", "black"],
      sizes: ["XL", "XXL"],
      images: {
        front: "./src/image/clothing/insert-sweat-1.png",
        back: "./src/image/clothing/insert-sweat-2.png",
      },
      stock: 12,
    },
    {
      id: 4,
      title: "Casual Tee",
      price: 20,
      colors: ["green", "yellow"],
      sizes: ["M", "L"],
      images: {
        front: "./src/image/clothing/heritage-crew-tshirt-1.jpg",
        back: "./src/image/clothing/heritage-crew-tshirt-2.jpg",
      },
      stock: 8,
    },
    {
      id: 5,
      title: "Sport Tech",
      price: 95,
      colors: ["blue", "black"],
      sizes: ["S", "L"],
      images: {
        front: "./src/image/clothing/insert-nike-1.jpg",
        back: "./src/image/clothing/insert-nike-2.jpg",
      },
      stock: 5,
    },
    {
      id: 6,
      title: "Daily Wear",
      price: 30,
      colors: ["pink", "orange"],
      sizes: ["XS", "S"],
      images: {
        front: "./src/image/clothing/insert-sweat-1.png",
        back: "./src/image/clothing/insert-sweat-2.png",
      },
      stock: 20,
    },
    {
      id: 7,
      title: "Heavy Cotton",
      price: 55,
      colors: ["gray", "white"],
      sizes: ["M", "XL"],
      images: {
        front: "./src/image/clothing/heritage-crew-tshirt-1.jpg",
        back: "./src/image/clothing/heritage-crew-tshirt-2.jpg",
      },
      stock: 14,
    },
    {
      id: 8,
      title: "Urban Style",
      price: 60,
      colors: ["black", "yellow"],
      sizes: ["L", "XXL"],
      images: {
        front: "./src/image/clothing/insert-nike-1.jpg",
        back: "./src/image/clothing/insert-nike-2.jpg",
      },
      stock: 7,
    },
  ],
  dresses: [
    {
      id: 1,
      title: "Fashion Boutique",
      price: 120,
      colors: ["pink", "yellow"],
      sizes: ["XS", "S"],
      images: {
        front: "./src/image/clothing/fashion-boutique-1.jpg",
        back: "./src/image/clothing/fashion-boutique-2.jpg",
      },
      stock: 5,
    },
    {
      id: 2,
      title: "Linen Summer",
      price: 95,
      colors: ["white", "orange"],
      sizes: ["S", "M"],
      images: {
        front: "./src/image/clothing/insert-linen-1.jpg",
        back: "./src/image/clothing/insert-linen-2.jpg",
      },
      stock: 8,
    },
    {
      id: 3,
      title: "Floral Dream",
      price: 110,
      colors: ["blue", "green"],
      sizes: ["M", "L"],
      images: {
        front: "./src/image/clothing/insert-crochet-1.jpg",
        back: "./src/image/clothing/insert-crochet-2.jpg",
      },
      stock: 3,
    },
    {
      id: 4,
      title: "Evening Gala",
      price: 200,
      colors: ["black", "red"],
      sizes: ["S", "M", "L"],
      images: {
        front: "./src/image/clothing/fashion-boutique-1.jpg",
        back: "./src/image/clothing/fashion-boutique-2.jpg",
      },
      stock: 2,
    },
    {
      id: 5,
      title: "Beach Vibes",
      price: 45,
      colors: ["yellow", "white"],
      sizes: ["XS", "S"],
      images: {
        front: "./src/image/clothing/insert-linen-1.jpg",
        back: "./src/image/clothing/insert-linen-2.jpg",
      },
      stock: 12,
    },
    {
      id: 6,
      title: "Boho Chic",
      price: 88,
      colors: ["pink", "blue"],
      sizes: ["M", "L"],
      images: {
        front: "./src/image/clothing/insert-crochet-1.jpg",
        back: "./src/image/clothing/insert-crochet-2.jpg",
      },
      stock: 6,
    },
    {
      id: 7,
      title: "Silk Touch",
      price: 150,
      colors: ["gray", "black"],
      sizes: ["S", "M"],
      images: {
        front: "./src/image/clothing/fashion-boutique-1.jpg",
        back: "./src/image/clothing/fashion-boutique-2.jpg",
      },
      stock: 4,
    },
    {
      id: 8,
      title: "Morning Mist",
      price: 75,
      colors: ["blue", "white"],
      sizes: ["M", "XL"],
      images: {
        front: "./src/image/clothing/insert-linen-1.jpg",
        back: "./src/image/clothing/insert-linen-2.jpg",
      },
      stock: 9,
    },
  ],
  pants: [
    {
      id: 1,
      title: "Germain Trouser",
      price: 65,
      colors: ["black", "gray"],
      sizes: ["M", "L"],
      images: {
        front: "./src/image/clothing/insert-germain-1.jpg",
        back: "./src/image/clothing/insert-germain-2.jpg",
      },
      stock: 12,
    },
    {
      id: 2,
      title: "Seam Detail Pant",
      price: 55,
      colors: ["blue", "black"],
      sizes: ["S", "M"],
      images: {
        front: "./src/image/clothing/insert-seam-1.jpg",
        back: "./src/image/clothing/insert-seam-2.jpg",
      },
      stock: 18,
    },
    {
      id: 3,
      title: "Cargo Pocket",
      price: 70,
      colors: ["green", "yellow"],
      sizes: ["L", "XL"],
      images: {
        front: "./src/image/clothing/insert-germain-1.jpg",
        back: "./src/image/clothing/insert-germain-2.jpg",
      },
      stock: 10,
    },
    {
      id: 4,
      title: "Slim Chino",
      price: 40,
      colors: ["orange", "gray"],
      sizes: ["M", "L"],
      images: {
        front: "./src/image/clothing/insert-seam-1.jpg",
        back: "./src/image/clothing/insert-seam-2.jpg",
      },
      stock: 15,
    },
    {
      id: 5,
      title: "Wide Leg",
      price: 80,
      colors: ["black", "white"],
      sizes: ["S", "M"],
      images: {
        front: "./src/image/clothing/insert-germain-1.jpg",
        back: "./src/image/clothing/insert-germain-2.jpg",
      },
      stock: 6,
    },
    {
      id: 6,
      title: "Denim Classic",
      price: 90,
      colors: ["blue", "gray"],
      sizes: ["L", "XL"],
      images: {
        front: "./src/image/clothing/insert-seam-1.jpg",
        back: "./src/image/clothing/insert-seam-2.jpg",
      },
      stock: 20,
    },
    {
      id: 7,
      title: "Jogger Sport",
      price: 35,
      colors: ["black", "red"],
      sizes: ["M", "XL"],
      images: {
        front: "./src/image/clothing/insert-germain-1.jpg",
        back: "./src/image/clothing/insert-germain-2.jpg",
      },
      stock: 25,
    },
    {
      id: 8,
      title: "Vintage Corduroy",
      price: 110,
      colors: ["yellow", "orange"],
      sizes: ["S", "M"],
      images: {
        front: "./src/image/clothing/insert-seam-1.jpg",
        back: "./src/image/clothing/insert-seam-2.jpg",
      },
      stock: 4,
    },
  ],
  shirt: [
    {
      id: 1,
      title: "Oxygen Shirt",
      price: 40,
      colors: ["white", "blue"],
      sizes: ["S", "M", "L"],
      images: {
        front: "./src/image/clothing/insert-oxygen-1.jpg",
        back: "./src/image/clothing/insert-oxygen-2.jpg",
      },
      stock: 25,
    },
    {
      id: 2,
      title: "Heritage Shirt",
      price: 42,
      colors: ["gray", "green"],
      sizes: ["M", "L"],
      images: {
        front: "./src/image/clothing/insert-heritage-1.jpg",
        back: "./src/image/clothing/insert-heritage-2.jpg",
      },
      stock: 14,
    },
    {
      id: 3,
      title: "Linen Button",
      price: 50,
      colors: ["white", "yellow"],
      sizes: ["L", "XL"],
      images: {
        front: "./src/image/clothing/insert-oxygen-1.jpg",
        back: "./src/image/clothing/insert-oxygen-2.jpg",
      },
      stock: 11,
    },
    {
      id: 4,
      title: "Checkered Retro",
      price: 38,
      colors: ["red", "black"],
      sizes: ["M", "L"],
      images: {
        front: "./src/image/clothing/insert-heritage-1.jpg",
        back: "./src/image/clothing/insert-heritage-2.jpg",
      },
      stock: 19,
    },
    {
      id: 5,
      title: "Office Smart",
      price: 65,
      colors: ["blue", "gray"],
      sizes: ["S", "M"],
      images: {
        front: "./src/image/clothing/insert-oxygen-1.jpg",
        back: "./src/image/clothing/insert-oxygen-2.jpg",
      },
      stock: 8,
    },
    {
      id: 6,
      title: "Summer Short",
      price: 30,
      colors: ["orange", "pink"],
      sizes: ["M", "XL"],
      images: {
        front: "./src/image/clothing/insert-heritage-1.jpg",
        back: "./src/image/clothing/insert-heritage-2.jpg",
      },
      stock: 22,
    },
    {
      id: 7,
      title: "Denim Shirt",
      price: 75,
      colors: ["blue", "black"],
      sizes: ["L", "XXL"],
      images: {
        front: "./src/image/clothing/insert-oxygen-1.jpg",
        back: "./src/image/clothing/insert-oxygen-2.jpg",
      },
      stock: 5,
    },
    {
      id: 8,
      title: "Silk Blend",
      price: 120,
      colors: ["white", "gray"],
      sizes: ["S", "M"],
      images: {
        front: "./src/image/clothing/insert-heritage-1.jpg",
        back: "./src/image/clothing/insert-heritage-2.jpg",
      },
      stock: 3,
    },
  ],
  shoes: [
    {
      id: 1,
      title: "Old Skool",
      price: 70,
      colors: ["black", "white"],
      sizes: ["M", "L"],
      images: {
        front: "./src/image/clothing/insert-skool-1.jpg",
        back: "./src/image/clothing/insert-skool-2.jpg",
      },
      stock: 9,
    },
    {
      id: 2,
      title: "Canvas Low",
      price: 45,
      colors: ["blue", "red"],
      sizes: ["S", "M"],
      images: {
        front: "./src/image/clothing/insert-canvas-1.jpg",
        back: "./src/image/clothing/insert-canvas-2.jpg",
      },
      stock: 15,
    },
    {
      id: 3,
      title: "Urban Sneaker",
      price: 130,
      colors: ["gray", "yellow"],
      sizes: ["L", "XL"],
      images: {
        front: "./src/image/clothing/insert-skool-1.jpg",
        back: "./src/image/clothing/insert-skool-2.jpg",
      },
      stock: 6,
    },
    {
      id: 4,
      title: "Sport Runner",
      price: 110,
      colors: ["black", "blue"],
      sizes: ["M", "L"],
      images: {
        front: "./src/image/clothing/insert-canvas-1.jpg",
        back: "./src/image/clothing/insert-canvas-2.jpg",
      },
      stock: 12,
    },
    {
      id: 5,
      title: "Daily Walk",
      price: 55,
      colors: ["white", "pink"],
      sizes: ["S", "M"],
      images: {
        front: "./src/image/clothing/insert-skool-1.jpg",
        back: "./src/image/clothing/insert-skool-2.jpg",
      },
      stock: 20,
    },
    {
      id: 6,
      title: "Street High",
      price: 95,
      colors: ["green", "black"],
      sizes: ["L", "XL"],
      images: {
        front: "./src/image/clothing/insert-canvas-1.jpg",
        back: "./src/image/clothing/insert-canvas-2.jpg",
      },
      stock: 8,
    },
    {
      id: 7,
      title: "Retro Tennis",
      price: 85,
      colors: ["white", "blue"],
      sizes: ["M", "L"],
      images: {
        front: "./src/image/clothing/insert-skool-1.jpg",
        back: "./src/image/clothing/insert-skool-2.jpg",
      },
      stock: 14,
    },
    {
      id: 8,
      title: "Comfy Slip",
      price: 40,
      colors: ["gray", "orange"],
      sizes: ["S", "M"],
      images: {
        front: "./src/image/clothing/insert-canvas-1.jpg",
        back: "./src/image/clothing/insert-canvas-2.jpg",
      },
      stock: 18,
    },
  ],
  vintage: [
    {
      id: 1,
      title: "Charlotte Trench",
      price: 150,
      colors: ["orange", "yellow"],
      sizes: ["M", "L"],
      images: {
        front: "./src/image/clothing/charlotte-trench-1.jpg",
        back: "./src/image/clothing/charlotte-trench-2.jpg",
      },
      stock: 3,
    },
    {
      id: 2,
      title: "Crochet Classic",
      price: 80,
      colors: ["green", "pink"],
      sizes: ["S", "M"],
      images: {
        front: "./src/image/clothing/insert-crochet-1.jpg",
        back: "./src/image/clothing/insert-crochet-2.jpg",
      },
      stock: 6,
    },
    {
      id: 3,
      title: "Parka Retro",
      price: 180,
      colors: ["black", "gray"],
      sizes: ["L", "XL"],
      images: {
        front: "./src/image/clothing/insert-parka-1.jpg",
        back: "./src/image/clothing/insert-parka-2.jpg",
      },
      stock: 2,
    },
    {
      id: 4,
      title: "Snapback Cap",
      price: 25,
      colors: ["blue", "red"],
      sizes: ["S", "M"],
      images: {
        front: "./src/image/clothing/insert-snapback-1.jpg",
        back: "./src/image/clothing/insert-snapback-2.jpg",
      },
      stock: 30,
    },
    {
      id: 5,
      title: "Oversized Parka",
      price: 165,
      colors: ["green", "black"],
      sizes: ["XL", "XXL"],
      images: {
        front: "./src/image/clothing/insert-parka-1.jpg",
        back: "./src/image/clothing/insert-parka-2.jpg",
      },
      stock: 5,
    },
    {
      id: 6,
      title: "Vintage Crochet",
      price: 75,
      colors: ["white", "blue"],
      sizes: ["M", "L"],
      images: {
        front: "./src/image/clothing/insert-crochet-1.jpg",
        back: "./src/image/clothing/insert-crochet-2.jpg",
      },
      stock: 7,
    },
    {
      id: 7,
      title: "Trench Coat",
      price: 140,
      colors: ["gray", "white"],
      sizes: ["S", "M"],
      images: {
        front: "./src/image/clothing/charlotte-trench-1.jpg",
        back: "./src/image/clothing/charlotte-trench-2.jpg",
      },
      stock: 4,
    },
    {
      id: 8,
      title: "Classic Snapback",
      price: 30,
      colors: ["black", "orange"],
      sizes: ["M", "L"],
      images: {
        front: "./src/image/clothing/insert-snapback-1.jpg",
        back: "./src/image/clothing/insert-snapback-2.jpg",
      },
      stock: 25,
    },
  ],
};
